// <auto-generated />
using ArtigoLogEFCore5;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ArtigoLogEFCore5.Migrations
{
    [DbContext(typeof(BancoContexto))]
    partial class BancoContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ArtigoLogEFCore5.Medico", b =>
                {
                    b.Property<int>("MedicoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Especialidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MedicoId");

                    b.ToTable("Medicos");

                    b.HasData(
                        new
                        {
                            MedicoId = 1,
                            Especialidade = "Infectologista",
                            Nome = "Marcelo"
                        },
                        new
                        {
                            MedicoId = 2,
                            Especialidade = "Ortopedista",
                            Nome = "Thiago"
                        },
                        new
                        {
                            MedicoId = 3,
                            Especialidade = "Ginecologista",
                            Nome = "Regina"
                        });
                });

            modelBuilder.Entity("ArtigoLogEFCore5.Paciente", b =>
                {
                    b.Property<int>("PacienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Covid")
                        .HasColumnType("bit");

                    b.Property<int>("MedicoId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PacienteId");

                    b.HasIndex("MedicoId");

                    b.ToTable("Pacientes");

                    b.HasData(
                        new
                        {
                            PacienteId = 1,
                            Covid = true,
                            MedicoId = 1,
                            Nome = "Renato"
                        },
                        new
                        {
                            PacienteId = 2,
                            Covid = true,
                            MedicoId = 1,
                            Nome = "Livia"
                        },
                        new
                        {
                            PacienteId = 3,
                            Covid = false,
                            MedicoId = 2,
                            Nome = "Ivete"
                        },
                        new
                        {
                            PacienteId = 4,
                            Covid = true,
                            MedicoId = 2,
                            Nome = "Rosi"
                        },
                        new
                        {
                            PacienteId = 5,
                            Covid = true,
                            MedicoId = 3,
                            Nome = "Reginaldo"
                        });
                });

            modelBuilder.Entity("ArtigoLogEFCore5.Paciente", b =>
                {
                    b.HasOne("ArtigoLogEFCore5.Medico", "Medico")
                        .WithMany("Pacientes")
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medico");
                });

            modelBuilder.Entity("ArtigoLogEFCore5.Medico", b =>
                {
                    b.Navigation("Pacientes");
                });
#pragma warning restore 612, 618
        }
    }
}
